#!/bin/sh

# backup (local)
#
# dump .sql & sync media/* to ~/
# add cron job on production server
# errors to $LOG

DATE=`date +%Y-%m-%d`
HOME_LOCAL="/Users/reinfurt"
WWW_LOCAL="/Library/Webserver/Documents/t-y-p-o-g-r-a-p-h-y.local"
BACKUP_LOCAL="$HOME_LOCAL/backup/t-y-p-o-g-r-a-p-h-y.local"
SQL="$BACKUP_LOCAL/$DATE.sql"
LOG="$WWW_LOCAL/static/bash/log"
DB_USER_LOCAL="root"
DB_PASS_LOCAL=""
DB_HOST_LOCAL="localhost"
DB_NAME_LOCAL="t_y_p_o_g_r_a_p_h_y_local"

echo "\n$DATE" >>$LOG
if [ ! -d "$BACKUP_LOCAL" ]; then
    mkdir $BACKUP_LOCAL 2>>$LOG;
    echo "$BACKUP_LOCAL created." 
fi
echo "\nStart mysqldump ..."
mysqldump -u $DB_USER_LOCAL -p$DB_PASS_LOCAL -h $DB_HOST_LOCAL $DB_NAME_LOCAL > $SQL 2>>$LOG
echo "\nStart rsync ..."
rsync -azP $WWW_LOCAL/media/ $BACKUP_LOCAL/media 2>>$LOG
